version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "get-saved-addresses"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-dyji3iya276r"
s3_prefix = "get-saved-addresses"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
